In [4]:
import pandas as pd

df = pd.read_csv("C:/Users/USER/Downloads/WA_Fn-UseC_-Telco-Customer-Churn.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
import os
os.path.expanduser("~")

'C:\\Users\\USER'

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [6]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df = df.dropna()

In [7]:
df.info()
df.shape
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [8]:
import numpy as np

rows = []

for _, row in df.iterrows():
    customer_id = row['customerID']
    tenure = int(row['tenure'])
    base_charge = row['MonthlyCharges']
    
    for month in range(1, tenure + 1):
        spend = base_charge * np.random.uniform(0.9, 1.1)
        
        rows.append([customer_id, month, round(spend, 2)])

time_df = pd.DataFrame(rows, columns=['customerID', 'month', 'monthly_spend'])

time_df.head()

   customerID  month  monthly_spend
0  7590-VHVEG      1          27.32
1  5575-GNVDE      1          58.51
2  5575-GNVDE      2          52.66
3  5575-GNVDE      3          58.17
4  5575-GNVDE      4          55.60

In [9]:
import numpy as np
import pandas as pd

rows = []

for _, row in df.iterrows():
    customer_id = row['customerID']
    tenure = int(row['tenure'])
    base_charge = row['MonthlyCharges']
    
    # Assign behavior
    behavior = np.random.choice(
        ['stable', 'decline', 'volatile', 'pre_churn'],
        p=[0.4, 0.3, 0.2, 0.1]
    )
    
    for month in range(1, tenure + 1):
        
        if behavior == 'stable':
            spend = base_charge * np.random.uniform(0.95, 1.05)
        
        elif behavior == 'decline':
            decay = 1 - (month / (tenure * 1.5))
            spend = base_charge * decay * np.random.uniform(0.95, 1.05)
        
        elif behavior == 'volatile':
            spend = base_charge * np.random.uniform(0.7, 1.3)
        
        elif behavior == 'pre_churn':
            if month > tenure * 0.7:
                spend = base_charge * np.random.uniform(0.4, 0.7)
            else:
                spend = base_charge * np.random.uniform(0.95, 1.05)
        
        rows.append([
            customer_id,
            month,
            round(spend, 2),
            behavior
        ])

time_df = pd.DataFrame(rows, columns=[
    'customerID',
    'month',
    'monthly_spend',
    'behavior_type'
])

time_df.head()

   customerID  month  monthly_spend behavior_type
0  7590-VHVEG      1          30.71        stable
1  5575-GNVDE      1          57.58       decline
2  5575-GNVDE      2          53.75       decline
3  5575-GNVDE      3          53.19       decline
4  5575-GNVDE      4          54.46       decline

In [10]:
time_df['rolling_avg_spend'] = (
    time_df.groupby('customerID')['monthly_spend']
    .transform(lambda x: x.rolling(window=3, min_periods=1).mean())
)

In [11]:
time_df['spend_change'] = (
    time_df.groupby('customerID')['rolling_avg_spend']
    .diff()
)

In [12]:
time_df['decline_flag'] = time_df['spend_change'] < 0

In [13]:
time_df['revenue_at_risk'] = np.where(
    time_df['decline_flag'],
    abs(time_df['spend_change']),
    0
)

In [14]:
customer_risk = time_df.groupby('customerID').agg({
    'revenue_at_risk': 'sum'
}).reset_index()

In [15]:
time_df.head(10)

,customerID,month,monthly_spend,behavior_type,rolling_avg_spend,spend_change,decline_flag,revenue_at_risk
0,7590-VHVEG,1,30.71,stable,30.710000,NaN,False,0.000000
1,5575-GNVDE,1,57.58,decline,57.580000,NaN,False,0.000000
2,5575-GNVDE,2,53.75,decline,55.665000,-1.915000,True,1.915000
3,5575-GNVDE,3,53.19,decline,54.840000,-0.825000,True,0.825000
4,5575-GNVDE,4,54.46,decline,53.800000,-1.040000,True,1.040000
5,5575-GNVDE,5,49.75,decline,52.466667,-1.333333,True,1.333333
6,5575-GNVDE,6,50.47,decline,51.560000,-0.906667,True,0.906667
7,5575-GNVDE,7,48.98,decline,49.733333,-1.826667,True,1.826667
8,5575-GNVDE,8,49.99,decline,49.813333,0.080000,False,0.000000
9,5575-GNVDE,9,47.83,decline,48.933333,-0.880000,True,0.880000

In [16]:
customer_summary = time_df.groupby('customerID').agg({
    'monthly_spend': 'mean',
    'revenue_at_risk': 'sum',
    'decline_flag': 'sum'
}).reset_index()

In [17]:
customer_summary['risk_score'] = (
    customer_summary['revenue_at_risk'] * 0.6 +
    customer_summary['monthly_spend'] * 0.3 +
    customer_summary['decline_flag'] * 0.1
)

In [18]:
customer_summary = customer_summary.sort_values(
    by='risk_score',
    ascending=False
)

In [19]:
customer_summary.head(10)

      customerID  monthly_spend  revenue_at_risk  decline_flag  risk_score
6943  9866-OCCKE     112.151111       338.300000            32  239.825333
2079  2988-QRAJY     108.876232       315.246667            38  225.610870
3802  5360-LJCNJ     103.718310       303.080000            37  216.663493
2550  3655-SNQYZ     112.962029       286.216667            34  209.018609
5687  8029-XYPWT     117.979296       283.090000            37  208.947789
6778  9637-CDTKZ     114.183611       283.648333            35  207.944083
115   0201-OAMXR     117.958143       281.166667            36  207.687443
1436  2121-JAFOM     121.940972       278.026667            38  207.198292
5868  8263-QMNTJ     116.392361       280.953333            35  206.989708
744   1090-PYKCI     107.552609       284.551667            38  206.796783

In [20]:
customer_summary['action_segment'] = pd.cut(
    customer_summary['risk_score'],
    bins=3,
    labels=['Monitor', 'At Risk', 'Urgent Action']
)

In [21]:
customer_summary['action_segment'].value_counts()

action_segment
Monitor          6491
At Risk           442
Urgent Action      99
Name: count, dtype: int64

In [22]:
def assign_action(row):
    if row['action_segment'] == 'Urgent Action':
        return 'Call / Retain Offer / Discount Intervention'
    elif row['action_segment'] == 'At Risk':
        return 'Engagement Campaign / Usage Incentive'
    else:
        return 'Monitor - No Action'

customer_summary['recommended_action'] = customer_summary.apply(assign_action, axis=1)

In [24]:
customer_summary.groupby('action_segment', observed=True)['risk_score'].mean()

action_segment
Monitor           32.677742
At Risk          112.679978
Urgent Action    182.483862
Name: risk_score, dtype: float64

In [25]:
customer_summary.sort_values('revenue_at_risk', ascending=False).head(10)

,customerID,monthly_spend,revenue_at_risk,decline_flag,risk_score,action_segment,recommended_action
6943,9866-OCCKE,112.151111,338.300000,32,239.825333,Urgent Action,Call / Retain Offer / Discount Intervention
2079,2988-QRAJY,108.876232,315.246667,38,225.610870,Urgent Action,Call / Retain Offer / Discount Intervention
3802,5360-LJCNJ,103.718310,303.080000,37,216.663493,Urgent Action,Call / Retain Offer / Discount Intervention
2550,3655-SNQYZ,112.962029,286.216667,34,209.018609,Urgent Action,Call / Retain Offer / Discount Intervention
744,1090-PYKCI,107.552609,284.551667,38,206.796783,Urgent Action,Call / Retain Offer / Discount Intervention
6778,9637-CDTKZ,114.183611,283.648333,35,207.944083,Urgent Action,Call / Retain Offer / Discount Intervention
5687,8029-XYPWT,117.979296,283.090000,37,208.947789,Urgent Action,Call / Retain Offer / Discount Intervention
115,0201-OAMXR,117.958143,281.166667,36,207.687443,Urgent Action,Call / Retain Offer / Discount Intervention
5868,8263-QMNTJ,116.392361,280.953333,35,206.989708,Urgent Action,Call / Retain Offer / Discount Intervention
1436,2121-JAFOM,121.940972,278.026667,38,207.198292,Urgent Action,Call / Retain Offer / Discount Intervention

In [27]:
customer_summary.groupby('action_segment', observed=True)['revenue_at_risk'].sum()

action_segment
Monitor          159512.773333
At Risk           61642.805000
Urgent Action     24276.641667
Name: revenue_at_risk, dtype: float64

In [28]:
customer_summary[
    customer_summary['monthly_spend'] > customer_summary['monthly_spend'].quantile(0.75)
].sort_values('risk_score', ascending=False).head(10)

,customerID,monthly_spend,revenue_at_risk,decline_flag,risk_score,action_segment,recommended_action
6943,9866-OCCKE,112.151111,338.300000,32,239.825333,Urgent Action,Call / Retain Offer / Discount Intervention
2079,2988-QRAJY,108.876232,315.246667,38,225.610870,Urgent Action,Call / Retain Offer / Discount Intervention
3802,5360-LJCNJ,103.718310,303.080000,37,216.663493,Urgent Action,Call / Retain Offer / Discount Intervention
2550,3655-SNQYZ,112.962029,286.216667,34,209.018609,Urgent Action,Call / Retain Offer / Discount Intervention
5687,8029-XYPWT,117.979296,283.090000,37,208.947789,Urgent Action,Call / Retain Offer / Discount Intervention
6778,9637-CDTKZ,114.183611,283.648333,35,207.944083,Urgent Action,Call / Retain Offer / Discount Intervention
115,0201-OAMXR,117.958143,281.166667,36,207.687443,Urgent Action,Call / Retain Offer / Discount Intervention
1436,2121-JAFOM,121.940972,278.026667,38,207.198292,Urgent Action,Call / Retain Offer / Discount Intervention
5868,8263-QMNTJ,116.392361,280.953333,35,206.989708,Urgent Action,Call / Retain Offer / Discount Intervention
744,1090-PYKCI,107.552609,284.551667,38,206.796783,Urgent Action,Call / Retain Offer / Discount Intervention

In [29]:
time_df.groupby('behavior_type')['revenue_at_risk'].sum()

behavior_type
decline       76389.006667
pre_churn     29572.733333
stable        36071.186667
volatile     103399.293333
Name: revenue_at_risk, dtype: float64

In [31]:
time_df = time_df.merge(
    customer_summary[['customerID', 'action_segment']],
    on='customerID',
    how='left'
)

In [32]:
time_df[time_df['action_segment'] == 'Urgent Action']['decline_flag'].mean()

np.float64(0.5050490050490051)

In [33]:
total_revenue = customer_summary['monthly_spend'].sum()

declining_revenue = customer_summary['revenue_at_risk'].sum()

declining_revenue / total_revenue

np.float64(0.6190376507934586)

In [34]:
customer_summary.sort_values('revenue_at_risk', ascending=False).head(10)

,customerID,monthly_spend,revenue_at_risk,decline_flag,risk_score,action_segment,recommended_action
6943,9866-OCCKE,112.151111,338.300000,32,239.825333,Urgent Action,Call / Retain Offer / Discount Intervention
2079,2988-QRAJY,108.876232,315.246667,38,225.610870,Urgent Action,Call / Retain Offer / Discount Intervention
3802,5360-LJCNJ,103.718310,303.080000,37,216.663493,Urgent Action,Call / Retain Offer / Discount Intervention
2550,3655-SNQYZ,112.962029,286.216667,34,209.018609,Urgent Action,Call / Retain Offer / Discount Intervention
744,1090-PYKCI,107.552609,284.551667,38,206.796783,Urgent Action,Call / Retain Offer / Discount Intervention
6778,9637-CDTKZ,114.183611,283.648333,35,207.944083,Urgent Action,Call / Retain Offer / Discount Intervention
5687,8029-XYPWT,117.979296,283.090000,37,208.947789,Urgent Action,Call / Retain Offer / Discount Intervention
115,0201-OAMXR,117.958143,281.166667,36,207.687443,Urgent Action,Call / Retain Offer / Discount Intervention
5868,8263-QMNTJ,116.392361,280.953333,35,206.989708,Urgent Action,Call / Retain Offer / Discount Intervention
1436,2121-JAFOM,121.940972,278.026667,38,207.198292,Urgent Action,Call / Retain Offer / Discount Intervention

In [35]:
threshold = customer_summary['risk_score'].quantile(0.9)

customer_summary[customer_summary['risk_score'] >= threshold]

,customerID,monthly_spend,revenue_at_risk,decline_flag,risk_score,action_segment,recommended_action
6943,9866-OCCKE,112.151111,338.300000,32,239.825333,Urgent Action,Call / Retain Offer / Discount Intervention
2079,2988-QRAJY,108.876232,315.246667,38,225.610870,Urgent Action,Call / Retain Offer / Discount Intervention
3802,5360-LJCNJ,103.718310,303.080000,37,216.663493,Urgent Action,Call / Retain Offer / Discount Intervention
2550,3655-SNQYZ,112.962029,286.216667,34,209.018609,Urgent Action,Call / Retain Offer / Discount Intervention
5687,8029-XYPWT,117.979296,283.090000,37,208.947789,Urgent Action,Call / Retain Offer / Discount Intervention
...,...,...,...,...,...,...,...
3372,4815-YOSUK,69.781111,75.806667,58,72.218333,Monitor,Monitor - No Action
3876,5461-QKNTN,80.632093,76.693333,20,72.205628,Monitor,Monitor - No Action
5140,7245-JMTTQ,73.298235,76.171667,45,72.192471,Monitor,Monitor - No Action
1310,1950-KSVVJ,74.978000,75.656667,43,72.187400,Monitor,Monitor - No Action
1742,2541-YGPKE,65.664048,83.616667,23,72.169214,Monitor,Monitor - No Action

In [37]:
customer_summary.groupby('action_segment', observed=True)['monthly_spend'].mean()

action_segment
Monitor           53.496257
At Risk           87.549527
Urgent Action    106.391157
Name: monthly_spend, dtype: float64

In [40]:
volatility = time_df.groupby('customerID')['monthly_spend'].std().reset_index()
volatility.columns = ['customerID', 'spend_volatility']

customer_volatility = customer_summary.merge(volatility, on='customerID', how='left')

customer_volatility.head()

,customerID,monthly_spend,revenue_at_risk,decline_flag,risk_score,action_segment,recommended_action,spend_volatility
0,9866-OCCKE,112.151111,338.300000,32,239.825333,Urgent Action,Call / Retain Offer / Discount Intervention,21.057418
1,2988-QRAJY,108.876232,315.246667,38,225.610870,Urgent Action,Call / Retain Offer / Discount Intervention,19.929338
2,5360-LJCNJ,103.718310,303.080000,37,216.663493,Urgent Action,Call / Retain Offer / Discount Intervention,18.462511
3,3655-SNQYZ,112.962029,286.216667,34,209.018609,Urgent Action,Call / Retain Offer / Discount Intervention,20.669156
4,8029-XYPWT,117.979296,283.090000,37,208.947789,Urgent Action,Call / Retain Offer / Discount Intervention,20.584628

In [41]:
customer_final = customer_summary[[
    'customerID',
    'monthly_spend',
    'revenue_at_risk',
    'risk_score',
    'action_segment',
    'recommended_action'
]]

In [42]:
customer_final.to_csv("mtn_customer_risk_dataset.csv", index=False)

In [43]:
time_final = time_df[[
    'customerID',
    'month',
    'monthly_spend',
    'behavior_type',
    'rolling_avg_spend',
    'spend_change',
    'decline_flag'
]]

In [44]:
time_final.to_csv("mtn_time_behavior_dataset.csv", index=False)

In [46]:
summary = customer_summary.groupby('action_segment', observed=True).agg(
    total_revenue_at_risk=('revenue_at_risk', 'sum'),
    customer_count=('customerID', 'count'),
    avg_risk_score=('risk_score', 'mean'),
    avg_spend=('monthly_spend', 'mean')
).reset_index()

In [47]:
summary.to_csv("mtn_risk_summary.csv", index=False)

In [48]:
import os
os.getcwd()

'C:\\Users\\USER'

In [49]:
customer_final.to_csv(r"C:\Users\USER\Downloads\mtn_customer_risk_dataset.csv", index=False)
time_final.to_csv(r"C:\Users\USER\Downloads\mtn_time_behavior_dataset.csv", index=False)
summary.to_csv(r"C:\Users\USER\Downloads\mtn_risk_summary.csv", index=False)